trigger: none
pool: RahulAgentPool
variables:
  backend_scn: 'RahulServiceConnection'   # Define the variable here
  config_path: '$(System.DefaultWorkingDirectory)/todoinfra'
parameters:
  - name: runVdate
    type: boolean
    default: true
  - name: runFmt
    type: boolean
    default: true
  - name: runplan
    type: boolean
    default: true
  - name: runApply
    type: boolean
    default: true

steps:
- task: TerraformInstaller@1
  displayName: 'Install terraform'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: 'Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(config_path)'
    backendServiceArm: '$(backend_scn)'
    backendAzureRmStorageAccountName: 'stgtest0076'
    backendAzureRmContainerName: 'statefiles'
    backendAzureRmKey: 'rahul.tfstate'
- task: TerraformTask@5
  displayName: 'terraform fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: '$(backend_scn)'
    if: eq(parameters.runFmt, true) 

- task: TerraformTask@5
  displayName: 'terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    if: eq(parameters.runVdate, true) 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: '$(backend_scn)'
   if: eq(parameters.runPlan, true) 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: '$(backend_scn)'
    if: eq(parameters.runApply, true) 



